# Generated by Django 4.1.6 on 2023-02-04 16:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=1023)),
                ('description', models.CharField(max_length=1023)),
                ('genres', models.CharField(max_length=1023)),
                ('uuid', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, default=uuid.uuid4, max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('accesstoken', models.CharField(default=uuid.uuid4, max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=255)),
                ('title', models.CharField(db_index=True, max_length=1023)),
                ('description', models.CharField(max_length=1023)),
                ('archive', models.CharField(db_index=True, max_length=1023)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('movies', models.ManyToManyField(to='moviesdata.movie')),
            ],
        ),
    ]
